ДЗ 1
jesterDLA/2019-2-Track-Frontend-D-Lapko pull request #1
Opened 2019-09-28 16:40 UTC by jesterDLA

# Домашнее задание №1

Прошу @martinkomitsky, @chexex или @priver проверить его.

Что было сделано:
*
*
*

2019-09-29 13:41 UTC, chexex commented
А можешь переместить содержимое директории `track-mail` вынести на уровень выше? Иначе получается лишний уровень вложенности и, например, сборщик не увидит файл travis.yml и не запустит сборку

2019-09-29 13:43 UTC, chexex requested changes
Нужно вынести содержимое track-mail наружу

2019-10-01 14:36 UTC, chexex requested changes
Сборка: подключить трэвис (добавить репу и ключ в travis-ci.org)
Другое: разрешить конфликты в репе (git rebase origin master или git merge origin master)

2019-10-06 11:58 UTC, chexex commented
Поправить сборку.
Сборка не проходит, потому что в travis-ci.ORG не добавлен токен. Полагаю, что токен был добавлен в travis-ci.ORG, а с гитом связан ORG :)

2019-10-06 17:11 UTC, jesterDLA commented
> Поправить сборку.
> Сборка не проходит, потому что в travis-ci.ORG не добавлен токен. Полагаю, что токен был добавлен в travis-ci.ORG, а с гитом связан ORG :)

Не понял вас. Токен добавлен на ORG, иначе бы сборка бы не запускалась... Есть ещё какие-то токены?

2019-10-06 18:10 UTC, chexex commented
> > Поправить сборку.
> > Сборка не проходит, потому что в travis-ci.ORG не добавлен токен. Полагаю, что токен был добавлен в travis-ci.ORG, а с гитом связан ORG :)
> 
> Не понял вас. Токен добавлен на ORG, иначе бы сборка бы не запускалась... Есть ещё какие-то токены?

Запуск сборки зависит от того, связал ли ты конкретный сборщик с репозиторием.

Что происходит в твоем случае.
![image](https://user-images.githubusercontent.com/16698238/66273536-7b60ac80-e87d-11e9-8a38-9457f1690012.png)
4 сборки:
2 с travis-ci.ORG
2 c travis-ci.COM

Одна из сборок не проходит (кликнув на детали, видно, что это travis-ci.com). Из-за того, что одна из сборок не проходит, даже не смотря на факт, что это одинаковые сборки, ВСЯ сборка считается не пройденной.

Выхода два:
1. Отвязать travis-ci.COM от репозитория
2. Кинуть в travis-ci.COM токен от гитхаба

В любом из этих случаев надо будет сделать коммит, чтобы заставить пересобираться проект.

2019-10-06 20:54 UTC, jesterDLA commented
> > > Поправить сборку.
> > > Сборка не проходит, потому что в travis-ci.ORG не добавлен токен. Полагаю, что токен был добавлен в travis-ci.ORG, а с гитом связан ORG :)
> > 
> > 
> > Не понял вас. Токен добавлен на ORG, иначе бы сборка бы не запускалась... Есть ещё какие-то токены?
> 
> Запуск сборки зависит от того, связал ли ты конкретный сборщик с репозиторием.
> 
> Что происходит в твоем случае.
> ![image](https://user-images.githubusercontent.com/16698238/66273536-7b60ac80-e87d-11e9-8a38-9457f1690012.png)
> 4 сборки:
> 2 с travis-ci.ORG
> 2 c travis-ci.COM
> 
> Одна из сборок не проходит (кликнув на детали, видно, что это travis-ci.com). Из-за того, что одна из сборок не проходит, даже не смотря на факт, что это одинаковые сборки, ВСЯ сборка считается не пройденной.
> 
> Выхода два:
> 
> 1. Отвязать travis-ci.COM от репозитория
> 2. Кинуть в travis-ci.COM токен от гитхаба
> 
> В любом из этих случаев надо будет сделать коммит, чтобы заставить пересобираться проект.

Ну это бред какой-то... Я уже не то что репозитории, но и сам аккаунт с .COM отвязал он все равно проверяет эти сборки

2019-10-06 21:03 UTC, jesterDLA commented
> > > > Поправить сборку.
> > > > Сборка не проходит, потому что в travis-ci.ORG не добавлен токен. Полагаю, что токен был добавлен в travis-ci.ORG, а с гитом связан ORG :)
> > > 
> > > 
> > > Не понял вас. Токен добавлен на ORG, иначе бы сборка бы не запускалась... Есть ещё какие-то токены?
> > 
> > 
> > Запуск сборки зависит от того, связал ли ты конкретный сборщик с репозиторием.
> > Что происходит в твоем случае.
> > ![image](https://user-images.githubusercontent.com/16698238/66273536-7b60ac80-e87d-11e9-8a38-9457f1690012.png)
> > 4 сборки:
> > 2 с travis-ci.ORG
> > 2 c travis-ci.COM
> > Одна из сборок не проходит (кликнув на детали, видно, что это travis-ci.com). Из-за того, что одна из сборок не проходит, даже не смотря на факт, что это одинаковые сборки, ВСЯ сборка считается не пройденной.
> > Выхода два:
> > 
> > 1. Отвязать travis-ci.COM от репозитория
> > 2. Кинуть в travis-ci.COM токен от гитхаба
> > 
> > В любом из этих случаев надо будет сделать коммит, чтобы заставить пересобираться проект.
> 
> Ну это бред какой-то... Я уже не то что репозитории, но и сам аккаунт с .COM отвязал он все равно проверяет эти сборки

Мда... Просто шок( Без токена и авторизации он продолжал тестить сборки, пришлось заново зайти и в ручную в настройках убрать галочки со сборок, больше ни на что он не реагирует.

2019-10-07 06:20 UTC, chexex approved these changes
Функции +
Тесты +
Сборка +

Спасибо за работу,
12 баллов

2019-10-07 06:20 UTC, merged